#thymeleafspring:
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5

# druid
  datasource:
      url: jdbc:mysql://111.230.131.178:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 12345678
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 1000
      initialSize: 100
      maxWait: 60000
      minIdle: 500
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#static
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
# mybatis
mybatis:
  type-aliases-package: com.hfuu.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/hfuu/miaosha/dao/*.xml

#redis
redis:
  host: 112.124.116.67
  password:
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500

#rabbitmq



